# Generated by Django 5.2 on 2026-05-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('panding', 'Panding'), ('in_prograss', 'In_Prograss'), ('done', 'Done')], default='panding', max_length=20)),
                ('priority', models.CharField(choices=[('medim', 'Meduim'), ('low', 'Low'), ('high', 'High')], default='meduim', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
