# Generated by Django 5.2 on 2026-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_priority_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('medim', 'Meduim'), ('low', 'Low'), ('high', 'High')], default='meduim', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('panding', 'Panding'), ('in_prograss', 'In_Prograss'), ('done', 'Done')], default='panding', max_length=20),
        ),
    ]
